export const translations = {
    es: {
      login: {
        title: 'Iniciar sesión',
        emailLabel: 'Correo electrónico',
        emailPlaceholder: 'Introduce tu correo electrónico',
        passwordLabel: 'Contraseña',
        passwordPlaceholder: 'Introduce tu contraseña',
        loginButton: 'Iniciar sesión',
        modalTitleSuccess: 'Inicio de sesión con éxito',
        modalMessageSuccess: 'Bienvenido/a, ',
        modalTitleError: 'Error con el inicio de sesión',
        modalMessageError: 'Error al iniciar sesión. Por favor, verifica tus credenciales y que la cuenta esté ya creada.',
        closeModalButton: 'Cerrar',
        goBackButton: 'Volver al inicio',
        forgotPassword: '¿Olvidaste tu contraseña?',
        resetPasswordButton: 'Restablecer contraseña',
      },
      register: {
        title: "Registro",
        emailLabel: "Correo electrónico",
        emailPlaceholder: "Introduce tu correo electrónico",
        passwordLabel: "Contraseña",
        passwordPlaceholder: "Introduce tu contraseña",
        confirmPasswordLabel: "Confirma tu contraseña",
        confirmPasswordPlaceholder: "Confirma tu contraseña",
        passwordsMismatch: "Las contraseñas no coinciden",
        registerButton: "Registrarse",
        modalTitleError: "Error",
        modalTitleSuccess: "Registro con éxito.",
        modalMessageError: "Se ha notificado un error en el registro",
        modalMessageSuccess: "Se ha enviado un correo de verificación.",
        closeModalButton: "Cerrar",
        goBackButton: "Volver al inicio",
      },
      profile: {
        title: "Perfil del usuario",
        name: "Nombre",
        namePlaceholder: "Introduce tu nombre",
        lastName: "Apellidos",
        lastNamePlaceholder: "Introduce tus apellidos",
        birthDate: "Fecha de nacimiento",
        birthDatePlaceholder: 'Introduce tu fecha de nacimiento',
        healthCard: "Número de tarjeta sanitaria",
        healthCardPlaceholder: "Introduce el número de tarjeta",
        dni: "DNI",
        dniPlaceholder: "Introduce tu DNI",
        updateButton: "Actualizar perfil",
        cancelButton: "Cancelar",
        editButton: "Editar perfil",
        backButton: "Volver al inicio",
        modalTitle: "Mensaje",
        modalCloseButton: "Cerrar",
        loading: "Cargando...",
        errorUpdateProfile: "Error al actualizar el perfil.",
        successUpdateProfile: "Perfil actualizado con éxito.",
        formError: "Corrige los errores en el formulario.",
      },
    },
    ca: {
      login: {
        title: 'Iniciar sessió',
        emailLabel: 'Correu electrònic',
        emailPlaceholder: 'Introdueix el teu correu electrònic',
        passwordLabel: 'Contrasenya',
        passwordPlaceholder: 'Introdueix la teva contrasenya',
        loginButton: 'Iniciar sessió',
        modalTitleSuccess: 'Inici de sessió amb èxit',
        modalMessageSuccess: 'Benvingut, ',
        modalTitleError: 'Error amb l\'inici de sessió',
        modalMessageError: 'Error en iniciar sessió. Si us plau, verifica les teves credencials i que el compte estigui ja creat.',
        closeModalButton: 'Tancar',
        goBackButton: 'Tornar a l\'inici',
        forgotPassword: 'Has oblidat la teva contrasenya?',
        resetPasswordButton: 'Restablir contrasenya',
      },
      register: {
        title: "Registre",
        emailLabel: "Correu electrònic",
        emailPlaceholder: "Introdueix el teu correu electrònic",
        passwordLabel: "Contrasenya",
        passwordPlaceholder: "Introdueix la teva contrasenya",
        confirmPasswordLabel: "Confirma la teva contrasenya",
        confirmPasswordPlaceholder: "Confirma la teva contrasenya",
        passwordsMismatch: "Les contrasenyes no coincideixen",
        registerButton: "Registrar-se",
        modalTitleError: "Error",
        modalTitleSuccess: "Registre amb èxit",
        modalMessageError: "S'ha notificat un error al registre",
        modalMessageSuccess: "S'ha enviat un correu de verificació.",
        closeModalButton: "Tancar",
        goBackButton: "Tornar a l'inici",
      },
      profile: {
        title: "Perfil de l'usuari",
        name: "Nom",
        namePlaceholder: "Introdueix el teu nom",
        lastName: "Cognoms",
        lastNamePlaceholder: "Introdueix els teus cognoms",
        birthDate: "Data de naixement",
        birthDatePlaceholder: 'Introdueix la teva data de naixement',
        healthCard: "Número de targeta sanitària",
        healthCardPlaceholder: "Introdueix el número de targeta",
        dni: "DNI",
        dniPlaceholder: "Introdueix el teu DNI",
        updateButton: "Actualitzar perfil",
        cancelButton: "Cancel·lar",
        editButton: "Editar perfil",
        backButton: "Torna a l'inici",
        modalTitle: "Missatge",
        modalCloseButton: "Tancar",
        loading: "Carregant...",
        errorUpdateProfile: "Error en actualitzar el perfil.",
        successUpdateProfile: "Perfil actualitzat amb èxit.",
        formError: "Corregeix els errors en el formulari.",
      },
    },
  };
