export const translations = {
    es: {
      login: {
        title: 'Iniciar sesión',
        emailLabel: 'Correo electrónico',
        emailPlaceholder: 'Introduce tu correo electrónico',
        passwordLabel: 'Contraseña',
        passwordPlaceholder: 'Introduce tu contraseña',
        loginButton: 'Iniciar sesión',
        modalTitleSuccess: 'Inicio de sesión con éxito',
        modalMessageSuccess: 'Bienvenido/a, ',
        modalTitleError: 'Error con el inicio de sesión',
        modalMessageError: 'Error al iniciar sesión. Por favor, verifica tus credenciales y que la cuenta esté ya creada.',
        closeModalButton: 'Cerrar',
        goBackButton: 'Volver al inicio',
        forgotPassword: '¿Olvidaste tu contraseña?',
        resetPasswordButton: 'Restablecer contraseña',
      },
      register: {
        title: "Registro",
        emailLabel: "Correo electrónico",
        emailPlaceholder: "Introduce tu correo electrónico",
        passwordLabel: "Contraseña",
        passwordPlaceholder: "Introduce tu contraseña",
        confirmPasswordLabel: "Confirma tu contraseña",
        confirmPasswordPlaceholder: "Confirma tu contraseña",
        passwordsMismatch: "Las contraseñas no coinciden",
        registerButton: "Registrarse",
        modalTitleError: "Error",
        modalTitleSuccess: "Registro con éxito.",
        modalMessageError: "Se ha notificado un error en el registro",
        modalMessageSuccess: "Se ha enviado un correo de verificación.",
        closeModalButton: "Cerrar",
        goBackButton: "Volver al inicio",
      },
      profile: {
        title: "Perfil del usuario",
        name: "Nombre",
        namePlaceholder: "Introduce tu nombre",
        lastName: "Apellidos",
        lastNamePlaceholder: "Introduce tus apellidos",
        birthDate: "Fecha de nacimiento",
        birthDatePlaceholder: 'Introduce tu fecha de nacimiento',
        healthCard: "Número de tarjeta sanitaria",
        healthCardPlaceholder: "Introduce el número de tarjeta (formato de ejemplo: AAAA 1 111111 11 1)",
        dni: "DNI",
        dniPlaceholder: "Introduce tu DNI",
        updateButton: "Actualizar perfil",
        cancelButton: "Cancelar",
        editButton: "Editar perfil",
        backButton: "Volver al inicio",
        modalTitle: "Mensaje",
        modalCloseButton: "Cerrar",
        loading: "Cargando...",
        errorUpdateProfile: "Error al actualizar el perfil.",
        successUpdateProfile: "Perfil actualizado con éxito.",
        formError: "Corrige los errores en el formulario.",
      },
      saludMental: {
        title: 'Información sobre salud mental',
        attentionProcesses: {
          title: 'Procesos de atención en salud mental',
          referral: 'Derivación desde Atención Primaria a psiquiatría:',
          referralDescription: 'El médico de cabecera evalúa la necesidad de una consulta especializada y realiza la derivación correspondiente a la Unidad de Salud Mental.',
          psychiatricEmergencies: 'Urgencias psiquiátricas:',
          psychiatricEmergenciesDescription: 'Las urgencias de salud mental se gestionan en servicios hospitalarios especializados que cuentan con personal capacitado para atender crisis inmediatas.',
          followUp: 'Seguimiento en consultas ambulatorias:',
          followUpDescription: 'Después de una evaluación inicial, los pacientes pueden ser atendidos en consultas programadas con especialistas en salud mental para continuar con su tratamiento.',
        },
        roles: {
          title: 'Roles en las Unidades de salud mental',
          psychiatrist: {
            title: 'Psiquiatría',
            description: 'Médico especialista en salud mental que diagnostica y trata trastornos psiquiátricos, incluyendo la prescripción de medicamentos.',
          },
          psychologist: {
            title: 'Psicología',
            description: 'Profesional que realiza evaluaciones psicológicas, terapia individual o grupal y estrategias de apoyo emocional.',
          },
          nurse: {
            title: 'Enfermería',
            description: 'Apoya en la gestión de tratamientos, seguimiento de pacientes y educación sobre la salud mental.',
          },
        },
        resources: {
          title: 'Recursos',
          contactPhones: 'Teléfonos de contacto:',
          suicidePrevention: 'Teléfono nacional de atención al suicidio:',
          mentalHealthLine: 'Línea de ayuda en salud mental:',
          specializedLinks: 'Enlaces a servicios especializados:',
          moreInfo: 'Sobre salud mental',
          psychiatryPortal: 'Portal de Psiquiatría',
        },
      },
    },
    ca: {
      login: {
        title: 'Iniciar sessió',
        emailLabel: 'Correu electrònic',
        emailPlaceholder: 'Introdueix el teu correu electrònic',
        passwordLabel: 'Contrasenya',
        passwordPlaceholder: 'Introdueix la teva contrasenya',
        loginButton: 'Iniciar sessió',
        modalTitleSuccess: 'Inici de sessió amb èxit',
        modalMessageSuccess: 'Benvingut/da, ',
        modalTitleError: 'Error amb l\'inici de sessió',
        modalMessageError: 'Error en iniciar sessió. Si us plau, verifica les teves credencials i que el compte estigui ja creat.',
        closeModalButton: 'Tancar',
        goBackButton: 'Tornar a l\'inici',
        forgotPassword: 'Has oblidat la teva contrasenya?',
        resetPasswordButton: 'Restablir contrasenya',
      },
      register: {
        title: "Registre",
        emailLabel: "Correu electrònic",
        emailPlaceholder: "Introdueix el teu correu electrònic",
        passwordLabel: "Contrasenya",
        passwordPlaceholder: "Introdueix la teva contrasenya",
        confirmPasswordLabel: "Confirma la teva contrasenya",
        confirmPasswordPlaceholder: "Confirma la teva contrasenya",
        passwordsMismatch: "Les contrasenyes no coincideixen",
        registerButton: "Registrar-se",
        modalTitleError: "Error",
        modalTitleSuccess: "Registre amb èxit",
        modalMessageError: "S'ha notificat un error al registre",
        modalMessageSuccess: "S'ha enviat un correu de verificació.",
        closeModalButton: "Tancar",
        goBackButton: "Tornar a l'inici",
      },
      profile: {
        title: "Perfil de l'usuari",
        name: "Nom",
        namePlaceholder: "Introdueix el teu nom",
        lastName: "Cognoms",
        lastNamePlaceholder: "Introdueix els teus cognoms",
        birthDate: "Data de naixement",
        birthDatePlaceholder: 'Introdueix la teva data de naixement',
        healthCard: "Número de targeta sanitària",
        healthCardPlaceholder: "Introdueix el número de targeta (format d'exemple: AAAA 1 111111 11 1)",
        dni: "DNI",
        dniPlaceholder: "Introdueix el teu DNI",
        updateButton: "Actualitzar perfil",
        cancelButton: "Cancel·lar",
        editButton: "Editar perfil",
        backButton: "Torna a l'inici",
        modalTitle: "Missatge",
        modalCloseButton: "Tancar",
        loading: "Carregant...",
        errorUpdateProfile: "Error en actualitzar el perfil.",
        successUpdateProfile: "Perfil actualitzat amb èxit.",
        formError: "Corregeix els errors en el formulari.",
      },
      saludMental: {
        title: 'Informació sobre salut mental',
        attentionProcesses: {
          title: 'Processos d\'atenció amb salut mental',
          referral: 'Derivació des de Atenció Primària a psiquiatria:',
          referralDescription: 'El metge de capçalera evalua la necessitat d\'una consulta especialitzada i realitza la derivació corresponent a la Unitat de Salut Mental.',
          psychiatricEmergencies: 'Urgències psiquiàtriques:',
          psychiatricEmergenciesDescription: 'Les urgències de salut mental es gestionen en serveis hospitalaris especialitzats amb personal capacitat para atendre crisis immediates.',
          followUp: 'Seguiment en consultes ambulatòries:',
          followUpDescription: 'Després d\'una evaluació inicial, els pacients poden ser atesos en consultes programades amb especialistes en salut mental per a continuar amb el seu tratament.',
        },
        roles: {
          title: 'Rols en les Unitats de salut mental',
          psychiatrist: {
            title: 'Psiquiatria',
            description: 'Metge especialista en salut mental que diagnostica i trata trastorns psiquiàtrics, incloent la prescripció de medicaments.',
          },
          psychologist: {
            title: 'Psicologia',
            description: 'Professional que realitza evaluacions psicològiques, teràpia individual o grupal i estratègies de suport emocional.',
          },
          nurse: {
            title: 'Enfermeria',
            description: 'Dona suport amb la gestió de trataments, seguiment de pacients i educació sobre la salut mental.',
          },
        },
        resources: {
          title: 'Recursos',
          contactPhones: 'Telèfons de contacte:',
          suicidePrevention: 'Telèfon nacional d\'atenció al suïcidi:',
          mentalHealthLine: 'Línea d\'ajuda amb salut mental:',
          specializedLinks: 'Enllaços a serveis especializats:',
          moreInfo: 'Sobre salut mental',
          psychiatryPortal: 'Portal de Psiquiatria',
        },
      },
    },
  };
